name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git Sumbodule Update
      run: |
        git submodule update --remote --recursive
    - name: Install requirements
      run: sudo apt-get install -y cmake build-essential libboost-program-options-dev libboost-container-dev libjsoncpp-dev uuid-dev
    - name: make
      run: |
        mkdir -p build
        cd build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make -j4 && cd ..
    - name: test
      run: |
        cd build && make test
